### ISSUE TITLE
Image Sequence Not playing while loading...

### ISSUE THREAD

**Issue by amirslayer** [truong-bui/AsyncLoadingScreen#33] opened 2021-07-24 09:36 UTC
hey there, I have set an image Sequence based on your Tutorials and it freezes on image index 0 until the game load is completed, then it starts playing!

**Comment by truong-bui** [comment] 2021-07-25 10:25
Well, it's weird. There are some people got problems with the Image Sequence loading icon but I'm not able to reproduce the issue on my side. I will investigate this, thanks.

**Comment by navdownsmash** [comment] 2021-08-20 02:41
Hi @amirslayer,
Can you share that project with @truong-bui? My PR may fix this bug in short term.

Regards
Nav

**Comment by truong-bui** [comment] 2021-08-20 03:53
I'll fix this issue and update to 4.27 in the weekend

**Comment by truong-bui** [comment] 2021-08-29 13:33
This's fixed in version 1.3.0, please update your plugin, thanks.

**Closed by truong-bui** 2021-08-29 13:33 UTC
